services:
  aveonline-connect-shoppify:
    build: .
    # env_file:
    #   - .env
    environment:
      SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
      SHOPIFY_API_SECRET: ${SHOPIFY_API_SECRET}
      SHOPIFY_SCOPES: ${SHOPIFY_SCOPES}
      SHOPIFY_APP_URL: ${SHOPIFY_APP_URL}
      SCOPES: ${SCOPES}
      NODE_ENV: production
    image: connect-shoppify  # <-- ¡Nueva línea clave!
    ports:
      - 3007:3000
    volumes:
      - .:/aveonline-connect-shopify
      - node_modules:/aveonline_connect_hopify/node_modules
    restart: always
volumes:
  node_modules: