# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04f9e383c62d9c03fc7db46b48100048"
name = "aveonline-connect"
handle = "aveonline-connect"
application_url = "https://solely-imagination-suburban-alot.trycloudflare.com"
embedded = true


[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = """
read_products,write_products,
read_product_listings,
read_product_feeds,write_product_feeds,

read_inventory,write_inventory,

read_orders,write_orders,
read_order_edits,write_order_edits,

read_draft_orders,write_draft_orders,

read_customers,write_customers,
read_customer_events,

read_fulfillments,write_fulfillments,
read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,
read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,

read_shipping,write_shipping,

read_discounts,write_discounts,
read_price_rules,write_price_rules,

read_gift_cards,write_gift_cards,

read_checkouts,write_checkouts,
read_cart_transforms,write_cart_transforms,
read_purchase_options,write_purchase_options,

read_themes,write_themes,
read_script_tags,write_script_tags,

read_content,write_content,

read_locales,write_locales,

read_reports,write_reports,

read_payment_customizations,write_payment_customizations,
read_payment_terms,write_payment_terms,

read_marketing_events,write_marketing_events,
read_analytics,

read_locations,write_locations,

read_shipping,write_shipping,
read_legal_policies,write_legal_policies
"""

[auth]
redirect_urls = ["https://solely-imagination-suburban-alot.trycloudflare.com/auth/callback", "https://solely-imagination-suburban-alot.trycloudflare.com/auth/shopify/callback", "https://solely-imagination-suburban-alot.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
